# Generated by Django 4.2.5 on 2023-10-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Имя')),
                ('desctiption', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категоря',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя продукта')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Изображение')),
                ('short_desc', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quintity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': ('Продукт',),
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
