# Generated by Django 4.2.5 on 2023-10-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='desctiption',
            new_name='description',
        ),
    ]
